// src/components/Map.tsx
import React, { useEffect, useRef, useState, useCallback } from 'react';
import { MapContainer, TileLayer, Marker, useMap, useMapEvents, Circle } from 'react-leaflet';
import { PhotoData, MapState } from '../types';
import { RotateCcw, RotateCw, ArrowLeftCircle, ArrowRightCircle } from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import L from 'leaflet';

// Create directional arrow icon
const createDirectionalArrow = (direction: number, color: string) => {
  // Create an SVG with an arrow pointing in the specified direction
  const svg = `
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <circle cx="12" cy="12" r="10" fill="${color}" fill-opacity="0.2" stroke="${color}" stroke-width="2"/>
      <path 
        transform="rotate(${direction} 12 12)"
        d="M12 6l4 6h-8z"
        fill="${color}"
      />
    </svg>
  `;

  return L.divIcon({
    className: 'photo-direction-arrow',
    html: svg,
    iconSize: [24, 24],
    iconAnchor: [12, 12],
  });
};

interface Props {
  photos: PhotoData[];
  onMapStateChange: (state: MapState) => void;
}

// Calculate visible distance based on zoom level
function calculateVisibleDistance(map: L.Map): number {
  const center = map.getCenter();
  const pointC = map.latLngToContainerPoint(center);
  
  // Get a point 100 pixels to the right of center
  const pointR = L.point(pointC.x + 100, pointC.y);
  
  // Convert back to LatLng
  const latLngR = map.containerPointToLatLng(pointR);
  
  // Calculate the distance between these points
  const distanceKm = center.distanceTo(latLngR) / 1000;
  
  // Scale the distance to match the circle radius (200px)
  return (distanceKm * 2);
}

function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth's radius in kilometers
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
    Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  return R * c;
}

function calculateBearing(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const lat1Rad = lat1 * Math.PI / 180;
  const lat2Rad = lat2 * Math.PI / 180;
  
  const y = Math.sin(dLon) * Math.cos(lat2Rad);
  const x = Math.cos(lat1Rad) * Math.sin(lat2Rad) -
            Math.sin(lat1Rad) * Math.cos(lat2Rad) * Math.cos(dLon);
  
  let bearing = Math.atan2(y, x) * 180 / Math.PI;
  bearing = (bearing + 360) % 360;
  return bearing;
}

function MapEventHandler({ onMapStateChange, photos }: { onMapStateChange: (state: MapState) => void; photos: PhotoData[] }) {
  const map = useMap();
  const bearingRef = useRef(0);

  const updateMapState = useCallback(() => {
    if (!map) return;
    const center = map.getCenter();
    onMapStateChange({
      center: [center.lat, center.lng],
      zoom: map.getZoom(),
      bearing: bearingRef.current,
      maxDistance: calculateVisibleDistance(map)
    });
  }, [map, onMapStateChange]);

  const rotateBearing = useCallback((degrees: number) => {
    if (!map) return;

    const newBearing = ((bearingRef.current + degrees + 360) % 360);
    bearingRef.current = newBearing;
    
    updateMapState();
  }, [map, updateMapState]);

  const rotateToNextPhoto = useCallback((direction: 'left' | 'right') => {
    if (!map) return;

    const center = map.getCenter();
    const currentBearing = bearingRef.current;
    const maxDistance = calculateVisibleDistance(map);

    // Calculate relative bearings to all photos within the visible range
    const photoBearings = photos
      .map(photo => {
        const distance = calculateDistance(
          center.lat,
          center.lng,
          photo.latitude,
          photo.longitude
        );

        // Skip photos outside the visible range
        if (distance > maxDistance) {
          return null;
        }

        const bearing = calculateBearing(
          center.lat,
          center.lng,
          photo.latitude,
          photo.longitude
        );
        
        // Calculate relative bearing (-180 to 180)
        let relativeBearing = ((bearing - currentBearing + 180 + 360) % 360) - 180;
        
        // For right rotation, we want the next photo clockwise
        // For left rotation, we want the next photo counterclockwise
        if (direction === 'right') {
          // If the relative bearing is negative, add 360 to make it positive for comparison
          if (relativeBearing < 0) relativeBearing += 360;
        } else {
          // If the relative bearing is positive, subtract 360 to make it negative for comparison
          if (relativeBearing > 0) relativeBearing -= 360;
        }

        return {
          photo,
          bearing,
          relativeBearing,
          distance
        };
      })
      .filter((item): item is NonNullable<typeof item> => 
        item !== null && (
          direction === 'right' ? 
            item.relativeBearing > 0 : // For right rotation, find positive relative bearings
            item.relativeBearing < 0   // For left rotation, find negative relative bearings
        )
      )
      .sort((a, b) => 
        direction === 'right' ?
          a.relativeBearing - b.relativeBearing : // Sort ascending for right rotation
          b.relativeBearing - a.relativeBearing   // Sort descending for left rotation
      );

    if (photoBearings.length > 0) {
      const nextPhoto = photoBearings[0];
      const rotationNeeded = nextPhoto.relativeBearing;
      rotateBearing(direction === 'right' ? rotationNeeded : -rotationNeeded);
    }
  }, [map, photos, rotateBearing]);

  // Expose functions to window for button access
  (window as any).rotateBearing = rotateBearing;
  (window as any).rotateToNextPhoto = rotateToNextPhoto;

  useMapEvents({
    moveend: updateMapState,
    zoomend: updateMapState,
  });

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') {
        rotateBearing(-5);
      } else if (e.key === 'ArrowRight') {
        rotateBearing(5);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [rotateBearing]);

  return null;
}

function VisibilityCircle({ center, maxDistance }: { center: [number, number]; maxDistance: number }) {
  return (
    <Circle
      center={center}
      radius={maxDistance * 1000} // Convert km to meters
      pathOptions={{
        color: '#4A90E2',
        fillColor: '#4A90E2',
        fillOpacity: 0.1,
        weight: 1
      }}
    />
  );
}

function PhotoMarkers({ photos, bearing }: { photos: PhotoData[]; bearing: number }) {
  const map = useMap();
  const initialFitDone = useRef(false);

  useEffect(() => {
    if (photos.length > 0 && !initialFitDone.current && map) {
      const validPhotos = photos.filter(
        photo => !isNaN(photo.latitude) && !isNaN(photo.longitude)
      );

      if (validPhotos.length > 0) {
        const bounds = L.latLngBounds(validPhotos.map(p => [p.latitude, p.longitude]));
        map.fitBounds(bounds, { padding: [50, 50] });
        initialFitDone.current = true;
      }
    }
  }, [photos, map]);

  return (
    <>
      {photos.map(photo => {
        if (isNaN(photo.latitude) || isNaN(photo.longitude)) {
          return null;
        }

        // Calculate the difference between the viewer's bearing and the photo's direction
        let bearingDiff = ((photo.direction - bearing + 360) % 360);
        if (bearingDiff > 180) bearingDiff = bearingDiff - 360;

        // Choose color based on bearing difference
        let color;
        if (Math.abs(bearingDiff) <= 60) {
          color = '#4CAF50'; // Green for in view
        } else if (Math.abs(bearingDiff) >= 150) {
          color = '#F44336'; // Red for opposite direction
        } else {
          color = '#FF9800'; // Orange for out of view
        }

        return (
          <Marker
            key={photo.id}
            position={[photo.latitude, photo.longitude]}
            icon={createDirectionalArrow(photo.direction, color)}
            title={`Photo at ${photo.latitude.toFixed(6)}, ${photo.longitude.toFixed(6)}
Direction: ${photo.direction.toFixed(1)}°
Relative to viewer: ${bearingDiff.toFixed(1)}°`}
          />
        );
      })}
    </>
  );
}

function FOVOverlay({ bearing }: { bearing: number }) {
  const width = 300;
  const height = 300;
  const centerX = width / 2;
  const centerY = height / 2;
  const radius = 100; // Radius of the circle
  const arrowLength = radius - 20; // Length of the direction arrow

  // Calculate arrow endpoint using bearing
  const radians = (bearing - 90) * Math.PI / 180; // -90 to point up at 0 degrees
  const arrowX = centerX + Math.cos(radians) * arrowLength;
  const arrowY = centerY + Math.sin(radians) * arrowLength;

  return (
    <div className="absolute inset-0 pointer-events-none" style={{ zIndex: 30000 }}>
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
        <svg
          width={width}
          height={height}
          viewBox={`0 0 ${width} ${height}`}
          className="transition-transform duration-200"
        >
          {/* Draw the circle */}
          <circle
            cx={centerX}
            cy={centerY}
            r={radius}
            fill="rgba(74, 144, 226, 0.1)"
            stroke="rgb(74, 144, 226)"
            strokeWidth="2"
          />

          {/* Draw the direction arrow */}
          <line
            x1={centerX}
            y1={centerY}
            x2={arrowX}
            y2={arrowY}
            stroke="rgb(74, 144, 226)"
            strokeWidth="3"
            markerEnd="url(#arrowhead)"
          />

          {/* Arrow head definition */}
          <defs>
            <marker
              id="arrowhead"
              markerWidth="10"
              markerHeight="7"
              refX="9"
              refY="3.5"
              orient="auto"
            >
              <polygon
                points="0 0, 10 3.5, 0 7"
                fill="rgb(74, 144, 226)"
              />
            </marker>
          </defs>

          {/* Add a small dot at the center */}
          <circle
            cx={centerX}
            cy={centerY}
            r="3"
            fill="rgb(74, 144, 226)"
          />
        </svg>
      </div>
    </div>
  );
}

export function Map({ photos, onMapStateChange }: Props) {
  const [bearing, setBearing] = useState(0);
  const [mapState, setMapState] = useState<MapState>({
    center: [51.505, -0.09],
    zoom: 13,
    bearing: 0,
    maxDistance: 2
  });

  const handleMapStateChange = useCallback((state: MapState) => {
    setBearing(state.bearing);
    setMapState(state);
    onMapStateChange(state);
  }, [onMapStateChange]);

  return (
    <div className="relative w-full h-full">
      <MapContainer
        center={[51.505, -0.09]}
        zoom={13}
        className="w-full h-full"
      >
        <MapEventHandler onMapStateChange={handleMapStateChange} photos={photos} />
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <VisibilityCircle center={mapState.center} maxDistance={mapState.maxDistance} />
        <PhotoMarkers photos={photos} bearing={bearing} />
      </MapContainer>
      
      <FOVOverlay bearing={bearing} />
      
      <div className="absolute bottom-4 left-4 flex gap-2">
        <button
          onClick={() => (window as any).rotateToNextPhoto('left')}
          className="p-2 bg-white rounded-full shadow-lg hover:bg-gray-100 transition-colors"
          title="Rotate to next photo on the left"
          style={{ zIndex: 30000 }}
        >
          <ArrowLeftCircle className="w-5 h-5 text-gray-700" />
        </button>
        <button
          onClick={() => (window as any).rotateBearing(-15)}
          className="p-2 bg-white rounded-full shadow-lg hover:bg-gray-100 transition-colors"
          title="Rotate view 15° counterclockwise"
          style={{ zIndex: 30000 }}
        >
          <RotateCcw className="w-5 h-5 text-gray-700" />
        </button>
        <button
          onClick={() => (window as any).rotateBearing(15)}
          className="p-2 bg-white rounded-full shadow-lg hover:bg-gray-100 transition-colors"
          title="Rotate view 15° clockwise"
          style={{ zIndex: 30000 }}
        >
          <RotateCw className="w-5 h-5 text-gray-700" />
        </button>
        <button
          onClick={() => (window as any).rotateToNextPhoto('right')}
          className="p-2 bg-white rounded-full shadow-lg hover:bg-gray-100 transition-colors"
          title="Rotate to next photo on the right"
          style={{ zIndex: 30000 }}
        >
          <ArrowRightCircle className="w-5 h-5 text-gray-700" />
        </button>
      </div>

      <div className="absolute bottom-4 right-4 bg-white p-2 rounded shadow">
        <p className="text-sm">Use ← → arrow keys or buttons to rotate the view direction</p>
      </div>
    </div>
  );
}

// frontend/src/components/Map.svelte
<script lang="ts">
    import {onMount, onDestroy, tick} from 'svelte';
    import {Polygon, LeafletMap, TileLayer, Marker, Circle, ScaleControl} from 'svelte-leafletjs';
    import {LatLng} from 'leaflet';
    import {RotateCcw, RotateCw, ArrowLeftCircle, ArrowRightCircle, MapPin} from 'lucide-svelte';
    import L from 'leaflet';
    import {Coordinate} from "tsgeo/Coordinate";
    import 'leaflet/dist/leaflet.css';
    import Spinner from './Spinner.svelte';

    import {
        app,
        pos,
        update_pos,
        pos2,
        bearing,
        photos_in_area,
        photo_in_front,
        photo_to_left,
        photo_to_right,
        update_bearing,
        turn_to_photo_to
    } from "$lib/data.svelte.js";
    import {sources} from "$lib/sources.ts";

    import {get} from "svelte/store";

    let flying = false;
    let locationTrackingLoading = false;
    let locationApiEventFlashTimer = null;
    let locationApiEventFlash = false;
    let map;
    let elMap;
    const fov_circle_radius_px = 70;
    
    // Location tracking variables
    let locationTracking = false;
    let watchId = null;
    let userLocationMarker = null;
    let accuracyCircle = null;
    let userHeading = null;

    function createDirectionalArrow(photo) {
        let bearing = Math.round(photo.bearing);
        let color = photo.source.color;
        let frc = '';
        let arrow_color = color;
        let size = 100;
        let inner_size = $pos.zoom * 3;
        let outer_size = 100;
        /*if ($photo_to_left === photo || $photo_to_right === photo) {
            size = 55;
            //arrow_color = '#88f';
        } else*/
        let dashes = '';
        let fill = '';
        let stroke_width = 1;
        if ($photo_in_front === photo) {
            //dashes = 'stroke-dasharray="20 4"'
            dashes = 'stroke-dasharray="1 10"'
            frc = photo.bearing_color;
            fill = `fill="${color}"`;
            stroke_width = 6
            //arrow_color = 'blue';
        }
        const half = Math.round(size / 2);

        // Define arrow dimensions relative to the size.
        // Adjust these variables to easily control the arrow's shape.
        const arrowTipY_inner = inner_size * 0.1;      // Y coordinate for the arrow tip (top)
        const arrowBaseY_inner = inner_size * 0.8;    // Y coordinate for the arrow base
        const arrowWidth_inner = inner_size * 0.15;    // Horizontal offset from center (controls thinness)
        const arrowTipY_outer = outer_size * 0.12;
        const arrowBaseY_outer = inner_size * 0.82;
        const arrowWidth_outer = outer_size * 0.16;

        let svg = `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" fill="none" xmlns="http://www.w3.org/2000/svg">`;

        if (photo === $photo_in_front) {
            svg += `<polygon transform="rotate(${bearing} ${half} ${half})"
               points="
                 ${half},${arrowTipY_outer}
                 ${half + arrowWidth_outer},${arrowBaseY_outer}
                 ${half - arrowWidth_outer},${arrowBaseY_outer}"
               stroke="${frc}" stroke-linecap="round" stroke-width="${stroke_width}"   />`
        //      <line x1="${half}" y1="${arrowTipY_outer * 4}" x2="${half}" y2="${arrowBaseY_outer}" stroke="${frc}" stroke-width="${stroke_width}" ${dashes} />
        }

        svg += `<polygon transform="rotate(${bearing} ${half} ${half})"
               points="
                 ${half},${arrowTipY_inner}
                 ${half + arrowWidth_inner},${arrowBaseY_inner}
                 ${half - arrowWidth_inner},${arrowBaseY_inner}"
                 ${fill} fill-opacity=0.8
               stroke="${color}" stroke-width="1" />`

        svg += '</svg>';

        return L.divIcon({
            className: 'photo-direction-arrow',
            html: svg,
            iconSize: [size, size],
            iconAnchor: [half, half]
        });
    }

    // Calculate how many km are "visible" based on the current zoom/center
    function get_range(_center: LatLng) {
        const pointC = map.latLngToContainerPoint(_center);
        // Move 100px to the right
        const pointR = L.point(pointC.x + fov_circle_radius_px, pointC.y);
        const latLngR = map.containerPointToLatLng(pointR);
        // distanceTo returns meters
        return _center.distanceTo(latLngR);
    }

    pos.subscribe((v) => {
        if (!map) return;
        if (map.getCenter() !== v.center || map.getZoom() !== v.zoom) {
            console.log('setView', v.center, v.zoom);
            map.setView(new LatLng(v.center.lat, v.center.lng), v.zoom);
            onMapStateChange(true, 'pos.subscribe');
        }
    });

    async function mapStateUserEvent(event) {

        if (!flying) {
            let _center = map.getCenter();
            let p = get(pos);
            console.log('mapStateUserEvent:', event);
            if (p.center.lat != _center.lat || p.center.lng != _center.lng) {
                console.log('p.center:', p.center, '_center:', _center);
                console.log('disableLocationTracking');
                disableLocationTracking();
            }
        }
        await onMapStateChange(true, 'mapStateUserEvent');
    }


    async function onMapStateChange(force, reason) {
        await tick();
        let _center = map.getCenter();
        let _zoom = map.getZoom();
        console.log('onMapStateChange force:', force, 'reason:', reason, 'center:', _center, '_zoom:', _zoom);
        let p = get(pos);
        let new_v = {
            ...p,
            center: new Coordinate(_center.lat, _center.lng),
            zoom: _zoom,
            reason: `onMapStateChange(${force}, ${reason})`,
        };

        if (force?.type) { // event
        }

        if (force === true || p.center.lat !== new_v.center.lat || p.center.lng !== new_v.center.lng || p.zoom !== new_v.zoom) {
            update_pos((value) => {
                return new_v;
            });
            pos2.update((value) => {
                return {
                    ...value,
                    range: get_range(_center),
                    top_left: map.getBounds().getNorthWest(),
                    bottom_right: map.getBounds().getSouthEast()
                };
            });
        }
    }

    // Handle button clicks and prevent map interaction
    async function handleButtonClick(action, event) {
        event.preventDefault();
        event.stopPropagation();

        if (action === 'left') {
            await turn_to_photo_to('left');
        } else if (action === 'right') {
            await turn_to_photo_to('right');
        } else if (action === 'rotate-ccw') {
            update_bearing(-15);
        } else if (action === 'rotate-cw') {
            update_bearing(15);
        } else if (action === 'location') {
            toggleLocationTracking();
        }

        return false;
    }
    
    function disableLocationTracking() {
        if (locationTracking) {
            toggleLocationTracking();
        }
    }

    function toggleLocationTracking() {
        if (locationTracking) {
            stopLocationTracking();
        } else {
            startLocationTracking();
        }
        locationTracking = !locationTracking;
    }
    
    // Start tracking user location
    function startLocationTracking() {
        if (!navigator.geolocation) {
            alert("Geolocation is not supported by your browser");
            return;
        }

        locationTrackingLoading = true;
        
        // Get initial position
        navigator.geolocation.getCurrentPosition(
            updateUserLocation,
            (error) => {
                console.error("Error getting location:", error);
                alert(`Unable to get your location: ${error.message}`);
                locationTracking = false;
            },
            { enableHighAccuracy: true }
        );
        
        // Start watching position
        watchId = navigator.geolocation.watchPosition(
            updateUserLocation,
            (error) => {
                console.error("Error watching location:", error);
            },
            { enableHighAccuracy: true }
        );
    }
    
    // Stop tracking user location
    function stopLocationTracking() {
        locationTrackingLoading = false;
        if (watchId !== null) {
            navigator.geolocation.clearWatch(watchId);
            watchId = null;
        }
    }
    
    // Update user location on the map
    async function updateUserLocation(position) {
        const { latitude, longitude, accuracy, heading } = position.coords;

        console.log("updateUserLocation:", latitude, longitude, accuracy, heading);
        locationTrackingLoading = false;
        locationApiEventFlash = true;
        if (locationApiEventFlashTimer !== null) {
            clearTimeout(locationApiEventFlashTimer);
        }
        locationApiEventFlashTimer = setTimeout(() => {
            locationApiEventFlash = false;
        }, 100);
        
        // Update user heading if available
        if (heading !== null && heading !== undefined) {
            userHeading = heading;
            // Optionally update the app bearing based on user heading
            if (locationTracking) {
                update_bearing(userHeading);
            }
        }
        
        if (map) {
            const latLng = new L.LatLng(latitude, longitude);

            // Center map on user location if tracking is active
            if (locationTracking) {
                flying = true;
                update_pos((value) => {
                    return {
                        ...value,
                        center: new Coordinate(latitude, longitude),
                        reason: 'updateUserLocation'
                    };
                });
                await tick();
                map.flyTo(latLng);
                await tick();
                flying = false;
                
                // Update the app position
                update_pos((value) => {
                    return {
                        ...value,
                        center: new Coordinate(latitude, longitude),
                        reason: 'updateUserLocation'
                    };
                });
                
                // Update other state as needed
                //onMapStateChange(true, 'updateUserLocation');
            }
        }
    }

    $: map = elMap?.getMap();

    onMount(async () => {
        await console.log('Map component mounted');
        await onMapStateChange(true, 'mount');
        await console.log('Map component mounted - after onMapStateChange');
    });

    export function setView(center, zoom) {
        if (map) {
            map.setView(center, zoom);
        }
    }

    //import.meta.hot?.dispose(() => (map = null));

    onDestroy(() => {
        console.log('Map component destroyed');
        // Clean up geolocation watcher if active
        if (watchId !== null) {
            navigator.geolocation.clearWatch(watchId);
        }
    });

    function toggleSourceVisibility(sourceId) {
        sources.update(sources => {
            const source = sources.find(s => s.id === sourceId);
            if (source) {
                source.enabled = !source.enabled;
            }
            return sources;
        });
    }

    let width;
    let height;

    // For the bearing overlay arrow:
    let centerX;
    $: centerX = width / 2;
    let centerY;
    $: centerY = height / 2;
    let arrowLength = fov_circle_radius_px + 150;

    let arrow_radians;
    let arrowX;
    let arrowY;

    $: arrow_radians = ($bearing - 90) * Math.PI / 180; // shift so 0° points "up"
    $: arrowX = centerX + Math.cos(arrow_radians) * arrowLength;
    $: arrowY = centerY + Math.sin(arrow_radians) * arrowLength;

    const tileUrl = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";

</script>


<!-- The map container -->
<div bind:clientHeight={height} bind:clientWidth={width} class="map">
    <LeafletMap
            bind:this={elMap}
            events={{moveend: mapStateUserEvent, zoomend: mapStateUserEvent}}
            options={{center: [$pos.center.lat, $pos.center.lng], zoom: $pos.zoom}}
    >

        <ScaleControl options={{maxWidth: 100}} position="bottomleft"/>

        <!-- Base map tiles -->
        <TileLayer
                attribution="&copy; OpenStreetMap contributors"
                options={{
                    maxZoom: 23,
                    maxNativeZoom: 19,
                    }}
                url={tileUrl}
        />


        {#if $pos.center}
            <Circle
                    latLng={$pos.center}
                    radius={$pos2.range}
                    color="#4AE092"
                    fillColor="#4A90E2"
                    weight={1.8}
            />
            <!-- arrow -->
        {/if}

        <!-- Markers for photos -->
        {#each $photos_in_area as photo (photo.id)}
            <Marker
                    zIndexOffset={10000*180-photo.abs_bearing_diff*10000}
                    latLng={photo.coord}
                    icon={createDirectionalArrow(photo)}
                    title={`Photo at ${photo.coord.lat.toFixed(6)}, ${photo.coord.lng.toFixed(6)}\n
Direction: ${photo.bearing.toFixed(1)}°\n
(Relative: ${(photo.bearing - $bearing).toFixed(1)}°)`}
            />

        {/each}

        <div class="svg-overlay">
            <svg
                    height={height}
                    viewBox={`0 0 ${width} ${height}`}
                    width={width}
            >
                <!--                    <circle-->
                <!--                            cx={centerX}-->
                <!--                            cy={centerY}-->
                <!--                            r={radius}-->
                <!--                            fill="rgba(74, 144, 226, 0.1)"-->
                <!--                            stroke="rgb(74, 144, 226)"-->
                <!--                            strokeWidth="2"-->
                <!--                    />-->

                <line
                        marker-end="url(#arrowhead)"
                        stroke="rgb(74, 144, 226)"
                        stroke-width="3"
                        x1={centerX}
                        x2={arrowX}
                        y1={centerY}
                        y2={arrowY}
                />
                <defs>
                    <marker
                            id="arrowhead"
                            markerHeight="7"
                            markerWidth="10"
                            orient="auto"
                            refX="9"
                            refY="3.5"
                    >
                        <polygon
                                fill="rgb(74, 244, 74)"
                                points="0 0, 10 3.5, 0 7"
                        />
                    </marker>
                </defs>

                <!--                    <circle-->
                <!--                            cx={centerX}-->
                <!--                            cy={centerY}-->
                <!--                            r="3"-->
                <!--                            fill="rgb(74, 144, 226)"-->
                <!--                    />-->
            </svg>
        </div>


    </LeafletMap>

</div>

<!-- Rotation / navigation buttons -->
<div class="control-buttons-container">
    <div class="buttons" role="group">
        <button
                on:click={async (e) => {await handleButtonClick('left', e)}}
                title="Rotate to next photo on the left"
                disabled={!$photo_to_left}
        >
            <ArrowLeftCircle/>
        </button>

        <button
                on:click={async (e) => {await handleButtonClick('rotate-ccw', e)}}
                title="Rotate view 15° counterclockwise"
        >
            <RotateCcw/>
        </button>

        <button
                on:click={(e) => handleButtonClick('rotate-cw', e)}
                title="Rotate view 15° clockwise"
        >
            <RotateCw/>
        </button>

        <button
                on:click={(e) => handleButtonClick('right', e)}
                title="Rotate to next photo on the right"
                disabled={!$photo_to_right}
        >
            <ArrowRightCircle/>
        </button>
    </div>
</div>

<!-- Location tracking button -->
<div class="location-button-container">
    <button 
        class={locationTracking ? 'active' : ''}
        on:click={(e) => handleButtonClick('location', e)}
        title="Track my location"
        class:flash={locationApiEventFlash}
    >
        <MapPin />
        {#if locationTrackingLoading}
            <Spinner show={true} color="#4285F4"></Spinner>
        {/if}
    </button>
</div>

<div class="source-buttons-container">
    {#each $sources as source}
        <button
                class={source.enabled ? 'active' : ''}
                on:click={() => toggleSourceVisibility(source.id)}
                title={`Toggle ${source.name} visibility`}
        >
            <div class="source-icon" style="background-color: {source.color}"></div>
            {source.name}
            <Spinner show={source.enabled && !!source.requests.length} color="#4285F4"></Spinner>
        </button>
    {/each}
</div>

<style>


    .map {
        width: 100%;
        height: 100%;
        position: relative;
    }

    .control-buttons-container {
        position: absolute;
        bottom: 0;
        right: 0;
        z-index: 30000;
        pointer-events: none; /* This makes the container transparent to mouse events */
    }

    .buttons {
        display: flex;
        gap: 0.5rem;
        background-color: rgba(255, 255, 255, 0.9);
        padding: 0.15rem;
        border-radius: 0.5rem 0 0 0;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        pointer-events: auto; /* This makes the buttons clickable */
    }

    .buttons button {
        cursor: pointer;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 0.25rem;
        padding: 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: background-color 0.2s;
    }

    .buttons button:hover {
        background-color: #f0f0f0;
    }

    .buttons button:active {
        background-color: #e0e0e0;
    }
    
    .location-button-container {
        position: absolute;
        top: 0px;
        right: 10px;
        z-index: 30000;
    }
    
    .location-button-container button {
        cursor: pointer;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 0.25rem;
        padding: 0.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: all 0.2s;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    }

    .location-button-container button:hover {
        background-color: #f0f0f0;
    }
    
    .location-button-container button.active {
        background-color: #4285F4;
        color: white;
        border-color: #3367d6;
    }

    .location-button-container button.flash {
        border-radius: 100%;
    }


    .source-buttons-container {
        position: absolute;
        top: 50px;
        right: 10px;
        z-index: 30000;
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
        margin: 0;
        padding: 0;
    }

    .source-buttons-container button {
        cursor: pointer;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 0.25rem;
        padding: 0.4rem;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: all 0.2s;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    }

    .source-buttons-container button:hover {
        background-color: #f0f0f0;
    }

    .source-buttons-container button.active {
        background-color: #4285F4;
        color: white;
        border-color: #3367d6;
    }

    .svg-overlay {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 750;
    }

    .source-icon {
        width: 1rem;
        height: 1rem;
        border-radius: 5%;
        margin-right: 0.5rem;
        border: 1px solid #ccc;
    }


</style>
